### ISSUE TITLE
Docker deployment not working

### ISSUE THREAD

**Issue by dkuenne** [ownrecipes/OwnRecipes#84] opened 2022-12-10 13:31 UTC
**Environment infos**
OS: Debian 11 x64
Docker: Docker version 20.10.21, build baeda1f
Python: Python 3.9.2
Used way to setup: [Running the App](https://github.com/ownrecipes/OwnRecipes/blob/master/docs/Running_the_App.md#running-the-app) without using a special version with the "-t" parameter or external DB

---

Running `python3 ./quick-start.py` fails:
```
Creating the DB. This may take a minute...
ERROR: The Compose file './docker-prod.yml' is invalid because:
services.api.depends_on contains an invalid type, it should be an array
ERROR: Version mismatch: file ./docker-prod.yml specifies version 3.1 but extension file ./docker-prod.version.yml uses version 2.3
ERROR: Version mismatch: file ./docker-prod.yml specifies version 3.1 but extension file ./docker-prod.version.yml uses version 2.3
ERROR: Version mismatch: file ./docker-prod.yml specifies version 3.1 but extension file ./docker-prod.version.yml uses version 2.3
ERROR: Version mismatch: file ./docker-prod.yml specifies version 3.1 but extension file ./docker-prod.version.yml uses version 2.3
App started. Please wait ~30 seconds for the containers to come online.
```

I've changend the compose file version from 2.3 to 3.1 in `quick-start.py` and `docker-prod.override.yml`.
Also in the file `docker-prod.yml`I've removed line 22 and changed line 21 from `db:` to `- db`, since it else fails because "depends_on" in this configuration seems not to be supported with [compose version 3-3.8](https://stackoverflow.com/a/72520034):
```
ERROR: The Compose file './docker-prod.yml' is invalid because:
services.api.depends_on contains an invalid type, it should be an array
```

After that the containers get created and all are running except "ownrecipes_web_1" which just exits.
Running `docker container logs ID` the log only shows the following output:
```
Setting the following environment variables:
{
  REACT_APP_ADMIN_URL: 'http://<REDACTED>/admin',
  REACT_APP_API_URL: 'http://<REDACTED>'
}
```

**Comment by sepulzera** [comment] 2022-12-10 18:45
Thanks for the comprehensive information, great job! :+1: I will take a look into these version errors. For now, it seems that you got them resolved.

The container ownrecipes_web_1 will exit. This is intended behaviour. The container will initialize the web app and provide the build as volume, that is mounted into the nginx. Or with other phrase: your OwnRecipes instance should be up and running. I see that this is confusing and should be explained in the docs (-> [#85](https://github.com/ownrecipes/OwnRecipes/issues/85)).

If you run `docker ps` you should see the db, api and nginx running. With your browser of choice, you should be able to connect to the web-app via the configured url (see `.env.docker.production.api`, var `NODE_URL`).

If you can't reach the web-app, you could try to open the [admin site](https://github.com/ownrecipes/OwnRecipes/blob/master/docs/Admin_site.md). The admin site is unrelated to the web-app, thus we could rule out any problem with the web-app.

**Comment by dkuenne** [comment] 2022-12-11 01:55
Yes, this behaviour is confusing since the website reports an connection error ("Die Verbindung zum Server von OwnRecipes ist fehlgeschlagen. Bitte versuchen Sie es in wenigen Minuten erneut.") which led me to think it was the exiting container.

Trying to cat or tail `/var/log/nginx/error.log` in the nginx container freezes and doesn't output anything.

Admin frontend is working though after setting the superuser password.
Any idea what could be wrong / how I can debug what's wrong?

**Comment by sepulzera** [comment] 2022-12-11 09:41
> Yes, this behaviour is confusing since the website reports an connection error and isn't usable ("Die Verbindung zum Server von OwnRecipes ist fehlgeschlagen. Bitte versuchen Sie es in wenigen Minuten erneut.") which led me to think it was the exiting "web" container.

I see, thanks for bringing this to my attention.

> Admin frontend is working fine.

Okay good.

> Trying to cat or tail /var/log/nginx/error.log in the nginx container freezes and doesn't output anything.

That sounds weird. I am not quite sure what could causing this. Perhaps you could try to find out what is going wrong here?

> Any idea what could be wrong / how I can debug what's wrong?

Well. Your db, api and nginx seem to be running correctly. And you also can connect to the admin site and as it seems you can also log in to the admin site. As you've created the superuser, the connection between api and db seem to be working, too.

Also, your error message ("Die Verbindung zum Server von OwnRecipes ist fehlgeschlagen. Bitte versuchen Sie es in wenigen Minuten erneut.") indicates that your web-app is running and you can reach it, what is great. But your web-app can not send requests to the api. Please double check that your vars in `.env.docker.production.web` are correct. The var `REACT_APP_API_URL` is used to send the requests to the api, so there seems to be something wrong.

You can also open the browser developer tools (probably by pressing [F12]) and switch to the Network tab. (I recommend Firefox for this, as i find Chrome's Network tab confusing.) There you can gather more information about future requests made to the api (-> open the developer tools, Network tab first, then reload your web-app). You should see some requests handled by nginx directly (like css and js files), that are probably succeeding. And you should see there the failing request(s) to the api (probably `/ownrecipes-api/api/v1/news/entry/` and `/ownrecipes-api/api/v1/recipe/mini-browse/` when visiting the home page).

If you wouldn't mind, you could also share a screenshot of your web-app and the developer tools Network tab. That could help troubleshooting.

**Comment by dkuenne** [comment] 2022-12-11 13:56
The hint about the .env was correct, I did overlook the needed port.

By default all configs are made for using port 8000, in the `.env.docker.production.web` though there wasn't any port specified in the example URL and I've just replaced the example domain without realizing that the port is also needed here.

So in the file `.env.docker.production.web` line 5 should be:
`REACT_APP_API_URL=http://ownrecipes.domain.com:8000`
and line 7:
`REACT_APP_ADMIN_URL=http://ownrecipes.domain.com:8000/admin`

Regarding the nginx logs, I've found the reason [on stackoverflow](https://stackoverflow.com/a/30270035).
Logs aren't written to a log file but to stdout so cat / tail and so on can't work.
`docker logs <container-id>` can be used instead and I've successfully verified that this is working.

Thank you for your quick help, this can be closed :)

**Comment by sepulzera** [comment] 2022-12-11 15:54
Nice to hear! And thanks for your PR! There are quite some things going on here, and I would like to track and tackle them separately. Would you mind to split your PR into two, one for the docker configurations issue and one for thee env change? That would be awesome. :rocket: 

Btw, I am still puzzled that the depends_on fails on your system, but is working on mine. Would you please share your `docker-compose` version?

**Comment by dkuenne** [comment] 2022-12-11 18:49
Sure, done :+1: 

`docker-compose version` returns:
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```

**Comment by sepulzera** [comment] 2022-12-12 15:37
My system is running:

```
Linux Mint 21.0
Docker version 20.10.21, build baeda1f
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

For docker-compose 1.29.0 there was a change:
  `Added a depends_on condition to wait for successful service completion.`
And for docker-compose 1.27.0:
  `Merged 2.x and 3.x Compose formats and aligned with COMPOSE_SPEC schema.`

To sum up, currently the project requires at least docker-compose 1.29.0. On the one hand, I'd really like to support the docker-compose version 1.25.0, as it is shipped with the current debian LTS 11. But on the other hand I don't want to drop the `depends_on condition`. Removing it seems pretty much like removing the depends_on altogether (the db container will start and become unhealthy after few minutes, but all other container will start anyway, and the quick-start-script succeed with no error).

Instead, I think it would be better to keep it as it is, and add an information to the [Prerequisites](https://github.com/ownrecipes/OwnRecipes/blob/development/docs/Install_Prerequisites.md) and to the newly added [Troubleshooting guide](https://github.com/ownrecipes/OwnRecipes/blob/development/docs/Troubleshooting.md).

What do you think?

**Comment by dkuenne** [comment] 2022-12-16 22:41
Well, I agree, I'd guess it's better to keep it for docker-compose 1.29.0 and document it in case someone runs an older version (like me).
Thus only on the older version people _may_ run in problems due to unhealthy containers, although I think this shouldn't happen anyways(?).

**Comment by sepulzera** [comment] 2022-12-21 17:43
I've updated the docs to cover the [minimum requirement(s) for docker-compose](https://github.com/ownrecipes/OwnRecipes/blob/1473556de0f294f314b99de59cb652f17433c70c/docs/Install_Prerequisites.md#required-docker-compose-version). And I've added some lines on how to make this project run with docker-compose 1.25.0+. Furthermore, I've added a section to the [troubleshooting guide](https://github.com/ownrecipes/OwnRecipes/blob/1473556de0f294f314b99de59cb652f17433c70c/docs/Troubleshooting.md#docker-compose-throws-an-error).

I think that was the last missing piece to resolve this issue. If you have any more findings or additions to this, please leave a comment and I will re-open this issue.

Sincere thanks for your time and help, and Merry Christmas!

**Closed by sepulzera** 2022-12-21 17:43 UTC
Labels: bug, good first issue
